/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pulse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Pulse */
        get: operations["get_pulse_api_pulse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products */
        get: operations["list_products_api_products_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_products__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Product Stores */
        get: operations["list_product_stores_api_products__product_id__stores_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stores/{store_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Store */
        get: operations["get_store_api_stores__store_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evidence */
        get: operations["list_evidence_api_evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Receipt */
        post: operations["upload_receipt_api_evidence_receipt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/price-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Price List */
        post: operations["upload_price_list_api_evidence_price_list_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/shelf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Shelf Photo */
        post: operations["upload_shelf_photo_api_evidence_shelf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Manual Evidence */
        post: operations["submit_manual_evidence_api_evidence_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scan/identify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Identify Product */
        post: operations["identify_product_api_scan_identify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trends */
        get: operations["get_trends_api_analytics_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/unit-economics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Unit Economics */
        get: operations["get_unit_economics_api_analytics_unit_economics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_identify_product_api_scan_identify_post */
        Body_identify_product_api_scan_identify_post: {
            /**
             * Image
             * @description JPEG, PNG, or WebP product image.
             */
            image: string;
        };
        /** Body_upload_price_list_api_evidence_price_list_post */
        Body_upload_price_list_api_evidence_price_list_post: {
            /**
             * Image
             * @description JPEG, PNG, or WebP posted price-list image.
             */
            image: string;
            /**
             * Store Id
             * Format: uuid
             * @description Store where the price list was photographed.
             */
            store_id: string;
        };
        /** Body_upload_receipt_api_evidence_receipt_post */
        Body_upload_receipt_api_evidence_receipt_post: {
            /**
             * Image
             * @description JPEG, PNG, or WebP receipt image.
             */
            image: string;
        };
        /** Body_upload_shelf_photo_api_evidence_shelf_post */
        Body_upload_shelf_photo_api_evidence_shelf_post: {
            /**
             * Image
             * @description JPEG, PNG, or WebP shelf photo.
             */
            image: string;
        };
        /** ConfidenceBreakdown */
        ConfidenceBreakdown: {
            /** Score */
            score: number;
            /**
             * Band
             * @enum {string}
             */
            band: "high" | "medium" | "low";
            /** Factors */
            factors: components["schemas"]["ConfidenceFactor"][];
            /**
             * Capped
             * @default false
             */
            capped: boolean;
            /** Cap Reason */
            cap_reason?: string | null;
        };
        /** ConfidenceFactor */
        ConfidenceFactor: {
            /**
             * Name
             * @enum {string}
             */
            name: "volume" | "agreement" | "freshness" | "diversity";
            /** Score */
            score: number;
            /** Weight */
            weight: number;
            /** Detail */
            detail: string;
        };
        /** CostBenchmark */
        CostBenchmark: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Min Etb */
            min_etb: number;
            /** Max Etb */
            max_etb: number;
            /**
             * Unit
             * @description What one unit of this benchmark buys.
             */
            unit: string;
            /** Source */
            source: string;
        };
        /**
         * ErrorResponse
         * @description Every error this API returns, including 429, has this body.
         */
        ErrorResponse: {
            /** Detail */
            detail: string;
        };
        /** EvidenceDecision */
        EvidenceDecision: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Product Id */
            product_id?: string | null;
            /** Product Name */
            product_name: string;
            /** Price Etb */
            price_etb: number;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "partner" | "receipt" | "scrape" | "store_visit" | "shelf_photo" | "community";
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "pending" | "rejected";
            /** Reason */
            reason: string;
        };
        /** EvidenceLogItem */
        EvidenceLogItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Product Name */
            product_name: string;
            /** Store Name */
            store_name?: string | null;
            /** Price Etb */
            price_etb: number;
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "partner" | "receipt" | "scrape" | "store_visit" | "shelf_photo" | "community";
            /**
             * Status
             * @enum {string}
             */
            status: "accepted" | "pending" | "rejected";
            /** Rejection Reason */
            rejection_reason?: string | null;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** EvidenceLogResponse */
        EvidenceLogResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["EvidenceLogItem"][];
        };
        /** ExtractedLineItem */
        ExtractedLineItem: {
            /** Raw Text */
            raw_text: string;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
            /** Unit Price Etb */
            unit_price_etb: number;
            /** Total Price Etb */
            total_price_etb: number;
            /** Matched Product Id */
            matched_product_id?: string | null;
            /** Matched Product Name */
            matched_product_name?: string | null;
            /** Match Confidence */
            match_confidence: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /** Fixtures */
            fixtures: boolean;
            /**
             * Checked At
             * Format: date-time
             */
            checked_at: string;
        };
        /** HistoryPoint */
        HistoryPoint: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Price Etb */
            price_etb: number;
            /** Evidence Count */
            evidence_count: number;
        };
        /** ManualEvidenceRequest */
        ManualEvidenceRequest: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /**
             * Store Id
             * Format: uuid
             */
            store_id: string;
            /** Price Etb */
            price_etb: number;
            /**
             * Observed At
             * Format: date-time
             */
            observed_at: string;
            /**
             * Source Type
             * @default community
             * @enum {string}
             */
            source_type: "store_visit" | "community";
        };
        /** ManualEvidenceResponse */
        ManualEvidenceResponse: {
            decision: components["schemas"]["EvidenceDecision"];
        };
        /** NearbyStorePrice */
        NearbyStorePrice: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** District */
            district: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "supermarket" | "shop" | "online";
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Price Etb */
            price_etb: number;
            /** Confidence */
            confidence: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Distance M */
            distance_m?: number | null;
            /** Difference From Market Etb */
            difference_from_market_etb: number;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "cheap" | "fair" | "high";
        };
        /** NearbyStoresResponse */
        NearbyStoresResponse: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Market Price Etb */
            market_price_etb: number;
            /** Items */
            items: components["schemas"]["NearbyStorePrice"][];
        };
        /** PriceListExtraction */
        PriceListExtraction: {
            /**
             * Store Id
             * Format: uuid
             */
            store_id: string;
            /** Store Name */
            store_name: string;
            /** Observed On */
            observed_on?: string | null;
            /** Ocr Confidence */
            ocr_confidence: number;
            /** Items */
            items: components["schemas"]["ExtractedLineItem"][];
        };
        /** PriceListUploadResponse */
        PriceListUploadResponse: {
            extraction: components["schemas"]["PriceListExtraction"];
            /** Decisions */
            decisions: components["schemas"]["EvidenceDecision"][];
        };
        /** ProductDetail */
        ProductDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Canonical Name */
            canonical_name: string;
            /** Brand */
            brand: string;
            /**
             * Category
             * @enum {string}
             */
            category: "cooking_oil" | "sugar" | "rice" | "flour" | "salt" | "pasta" | "coffee" | "tea" | "milk" | "soap" | "detergent" | "toothpaste" | "shampoo" | "bottled_water";
            /** Size Label */
            size_label: string;
            /** Market Price Etb */
            market_price_etb: number;
            /** Confidence */
            confidence: number;
            /**
             * Confidence Band
             * @enum {string}
             */
            confidence_band: "high" | "medium" | "low";
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            /** Barcode */
            barcode?: string | null;
            /** Price Range Etb */
            price_range_etb: [
                number,
                number
            ];
            /** Evidence Count */
            evidence_count: number;
            /** Store Count */
            store_count: number;
            /** Spread Pct */
            spread_pct: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            confidence_breakdown: components["schemas"]["ConfidenceBreakdown"];
            /** Sources */
            sources: components["schemas"]["SourceSummary"][];
            /** History */
            history: components["schemas"]["HistoryPoint"][];
        };
        /** ProductIdentification */
        ProductIdentification: {
            /** Product Id */
            product_id?: string | null;
            /** Canonical Name */
            canonical_name: string;
            /** Brand */
            brand: string;
            /**
             * Category
             * @enum {string}
             */
            category: "cooking_oil" | "sugar" | "rice" | "flour" | "salt" | "pasta" | "coffee" | "tea" | "milk" | "soap" | "detergent" | "toothpaste" | "shampoo" | "bottled_water";
            /** Size Value */
            size_value: number;
            /**
             * Size Unit
             * @enum {string}
             */
            size_unit: "ml" | "l" | "g" | "kg" | "piece";
            /** Confidence */
            confidence: number;
            /**
             * Match Method
             * @enum {string}
             */
            match_method: "alias_exact" | "trigram" | "gemini" | "gemini_vision" | "new_product";
        };
        /** ProductListResponse */
        ProductListResponse: {
            /** Total */
            total: number;
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Items */
            items: components["schemas"]["ProductSummary"][];
        };
        /** ProductSummary */
        ProductSummary: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Canonical Name */
            canonical_name: string;
            /** Brand */
            brand: string;
            /**
             * Category
             * @enum {string}
             */
            category: "cooking_oil" | "sugar" | "rice" | "flour" | "salt" | "pasta" | "coffee" | "tea" | "milk" | "soap" | "detergent" | "toothpaste" | "shampoo" | "bottled_water";
            /** Size Label */
            size_label: string;
            /** Market Price Etb */
            market_price_etb: number;
            /** Confidence */
            confidence: number;
            /**
             * Confidence Band
             * @enum {string}
             */
            confidence_band: "high" | "medium" | "low";
            /** Thumbnail Url */
            thumbnail_url?: string | null;
        };
        /** ProductTrend */
        ProductTrend: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Product Name */
            product_name: string;
            /**
             * Direction
             * @enum {string}
             */
            direction: "up" | "down" | "stable";
            /** Change Pct */
            change_pct: number;
            /** Points */
            points: components["schemas"]["TrendPoint"][];
        };
        /** PulseMetrics */
        PulseMetrics: {
            /** Verified Prices Today */
            verified_prices_today: number;
            /** Products Covered */
            products_covered: number;
            /** Stores Reporting */
            stores_reporting: number;
            /** New Receipts Today */
            new_receipts_today: number;
            /** Average Confidence */
            average_confidence: number;
        };
        /** PulseMover */
        PulseMover: {
            /**
             * Product Id
             * Format: uuid
             */
            product_id: string;
            /** Product Name */
            product_name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "fastest_rising" | "largest_drop" | "most_stable" | "most_verified";
            /** Value */
            value: number;
            /** Display Value */
            display_value: string;
        };
        /** PulseResponse */
        PulseResponse: {
            metrics: components["schemas"]["PulseMetrics"];
            /** Movers */
            movers: components["schemas"]["PulseMover"][];
            /** Cheapest District */
            cheapest_district: string;
            /** Most Active Store */
            most_active_store: string;
        };
        /** ReceiptExtraction */
        ReceiptExtraction: {
            /** Store Name */
            store_name?: string | null;
            /** Observed On */
            observed_on?: string | null;
            /** Total Etb */
            total_etb?: number | null;
            /** Ocr Confidence */
            ocr_confidence: number;
            /** Items */
            items: components["schemas"]["ExtractedLineItem"][];
        };
        /** ReceiptUploadResponse */
        ReceiptUploadResponse: {
            extraction: components["schemas"]["ReceiptExtraction"];
            /** Decisions */
            decisions: components["schemas"]["EvidenceDecision"][];
        };
        /** ShelfExtraction */
        ShelfExtraction: {
            /** Raw Product Text */
            raw_product_text: string;
            /** Price Etb */
            price_etb: number;
            /** Matched Product Id */
            matched_product_id?: string | null;
            /** Matched Product Name */
            matched_product_name?: string | null;
            /** Ocr Confidence */
            ocr_confidence: number;
            /** Match Confidence */
            match_confidence: number;
        };
        /** ShelfUploadResponse */
        ShelfUploadResponse: {
            extraction: components["schemas"]["ShelfExtraction"];
            decision: components["schemas"]["EvidenceDecision"];
        };
        /** SourceEconomics */
        SourceEconomics: {
            /** Source Type */
            source_type: string;
            /** Observations */
            observations: number;
            /** Verified Observations */
            verified_observations: number;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Candidates Tokens */
            candidates_tokens: number;
            /** Total Tokens */
            total_tokens: number;
            /** Gemini Cost Etb */
            gemini_cost_etb: number;
            /** Cost Per Verified Observation Etb */
            cost_per_verified_observation_etb?: number | null;
        };
        /** SourceSummary */
        SourceSummary: {
            /**
             * Source Type
             * @enum {string}
             */
            source_type: "partner" | "receipt" | "scrape" | "store_visit" | "shelf_photo" | "community";
            /** Label */
            label: string;
            /** Count */
            count: number;
            /**
             * Newest Observed At
             * Format: date-time
             */
            newest_observed_at: string;
        };
        /** StoreDetail */
        StoreDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** District */
            district: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "supermarket" | "shop" | "online";
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Product Count */
            product_count: number;
            /**
             * Average Price Index
             * @description 100 is market average; below 100 is cheaper.
             */
            average_price_index: number;
            /**
             * Last Reported At
             * Format: date-time
             */
            last_reported_at: string;
        };
        /** TrendPoint */
        TrendPoint: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Price Etb */
            price_etb: number;
        };
        /** TrendsResponse */
        TrendsResponse: {
            /** Period Days */
            period_days: number;
            /** Items */
            items: components["schemas"]["ProductTrend"][];
        };
        /** UnitEconomicsResponse */
        UnitEconomicsResponse: {
            /** Period Days */
            period_days: number;
            /** Observations */
            observations: number;
            /** Verified Observations */
            verified_observations: number;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Candidates Tokens */
            candidates_tokens: number;
            /** Total Tokens */
            total_tokens: number;
            /** Gemini Cost Usd */
            gemini_cost_usd: number;
            /** Gemini Cost Etb */
            gemini_cost_etb: number;
            /** Cost Per Verified Observation Etb */
            cost_per_verified_observation_etb?: number | null;
            /** Usd To Etb */
            usd_to_etb: number;
            /** Gemini Input Usd Per Mtok */
            gemini_input_usd_per_mtok: number;
            /** Gemini Output Usd Per Mtok */
            gemini_output_usd_per_mtok: number;
            /** By Source */
            by_source: components["schemas"]["SourceEconomics"][];
            /** Benchmarks */
            benchmarks: components["schemas"]["CostBenchmark"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_pulse_api_pulse_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PulseResponse"];
                };
            };
        };
    };
    list_products_api_products_get: {
        parameters: {
            query?: {
                q?: string | null;
                category?: ("cooking_oil" | "sugar" | "rice" | "flour" | "salt" | "pasta" | "coffee" | "tea" | "milk" | "soap" | "detergent" | "toothpaste" | "shampoo" | "bottled_water") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductDetail"];
                };
            };
            /** @description No product with this id has a priced estimate. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_product_stores_api_products__product_id__stores_get: {
        parameters: {
            query?: {
                latitude?: number | null;
                longitude?: number | null;
                radius_m?: number;
            };
            header?: never;
            path: {
                product_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NearbyStoresResponse"];
                };
            };
            /** @description No product with this id has a priced estimate. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_store_api_stores__store_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                store_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreDetail"];
                };
            };
            /** @description No store with this id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_evidence_api_evidence_get: {
        parameters: {
            query?: {
                /** @description Filter by the gate decision. */
                status?: ("accepted" | "pending" | "rejected") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_receipt_api_evidence_receipt_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Anonymous device identifier used for rate limiting. */
                "X-Device-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_receipt_api_evidence_receipt_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptUploadResponse"];
                };
            };
            /** @description The image is larger than 8MB. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The image must be one of image/jpeg, image/png, image/webp. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The per-device or per-network upload limit was reached. The `Retry-After` header carries the wait in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The image could not be read; ask the shopper to retake it. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_price_list_api_evidence_price_list_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Anonymous device identifier used for rate limiting. */
                "X-Device-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_price_list_api_evidence_price_list_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriceListUploadResponse"];
                };
            };
            /** @description The report names a store that does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The image is larger than 8MB. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The image must be one of image/jpeg, image/png, image/webp. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The per-device or per-network upload limit was reached. The `Retry-After` header carries the wait in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The image could not be read; ask the shopper to retake it. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_shelf_photo_api_evidence_shelf_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Anonymous device identifier used for rate limiting. */
                "X-Device-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_shelf_photo_api_evidence_shelf_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShelfUploadResponse"];
                };
            };
            /** @description The tagged product is not in the catalog, so its price cannot be recorded. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The image is larger than 8MB. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The image must be one of image/jpeg, image/png, image/webp. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The per-device or per-network upload limit was reached. The `Retry-After` header carries the wait in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The image could not be read; ask the shopper to retake it. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    submit_manual_evidence_api_evidence_manual_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Anonymous device identifier used for rate limiting. */
                "X-Device-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualEvidenceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualEvidenceResponse"];
                };
            };
            /** @description The report names a product or store that does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The per-device or per-network upload limit was reached. The `Retry-After` header carries the wait in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    identify_product_api_scan_identify_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Anonymous device identifier used for rate limiting. */
                "X-Device-Id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_identify_product_api_scan_identify_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductIdentification"];
                };
            };
            /** @description The image is larger than 8MB. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The image must be one of image/jpeg, image/png, image/webp. */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The per-device or per-network upload limit was reached. The `Retry-After` header carries the wait in seconds. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The image could not be read; ask the shopper to retake it. */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_trends_api_analytics_trends_get: {
        parameters: {
            query?: {
                period_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_unit_economics_api_analytics_unit_economics_get: {
        parameters: {
            query?: {
                period_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitEconomicsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
